fix: Remove FilterButton from Leads toolbar
Error: 'The <FilterButton> component requires the <List filters> prop to be set'

FilterButton requires a filters prop on the parent <List>, which LeadsList
doesn't have. Removed FilterButton from LeadsTopToolbar and cleaned up
the unused import.